# Generated by Django 3.2.9 on 2021-12-01 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoapp', '0004_bookedslots_warehouse'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookedslots',
            name='isPaid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bookedslots',
            name='noOfSlots',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookedslots',
            name='timestampOfBooking',
            field=models.TimeField(auto_now_add=True),
            preserve_default=False,
        ),
    ]
