# Generated by Django 3.2.9 on 2021-12-01 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geoapp', '0005_auto_20211201_2348'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Shop',
        ),
        migrations.DeleteModel(
            name='WorldBorder',
        ),
    ]
